### PR TITLE
Fixes #27443 - display advanced filtering

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
needs https://github.com/theforeman/foreman_virt_who_configure/pull/110, cc @mbacovsky could your team pls take a look? not high prio but it's tiny, I expect the plugin to have the needed patch next week

**Review by ofedoren — APPROVED** [review]
Tested with https://github.com/theforeman/foreman_virt_who_configure/pull/110

**Comment by ares** [comment]
server side merged, feel free to merge this one as well :-)

**Comment by ofedoren** [comment]
@ares, I'd glad to, but I don't have the merge permissions :-(

**Comment by ofedoren** [comment]
@ares, thanks :) Merging.

**Pull request merged**
