### PR TITLE
Fixes #33483 - Add ability to create/update with Kubevirt

### PR DESCRIPTION
**Pull request by chris1984**
I set `hypervisor_servername/username` to nil when using kubevirt because when we create a Kubevirt config in the UI we set those values to nil since they do not appear in the ui and are not used with Kubevirt since that info is in the config file. Without them set to `nil` hammer requires those params when trying to use type kubevirt and fails to run the command.

We can see that from the POST API call here when I made one from the UI:

```ruby
14:37:40 rails.1   | 2021-09-13T14:37:40 [I|app|5c3938ee] Started POST "/foreman_virt_who_configure/configs" for 192.168.177.1 at 2021-09-13 14:37:40 -0400
14:37:40 rails.1   | 2021-09-13T14:37:40 [I|app|5c3938ee] Processing by ForemanVirtWhoConfigure::ConfigsController#create as HTML
14:37:40 rails.1   | 2021-09-13T14:37:40 [I|app|5c3938ee]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"DeGnALlb+C21L9RakAz1UltIynP28hNLjCqws/uk4MQI7NxW21dpXYcxHu3H/5n18BmJY17UBqTMK4RU1KtWlA==", "foreman_virt_who_configure_config"=>{"name"=>"test", "organization_id"=>"1", "hypervisor_type"=>"kubevirt", "hypervisor_server"=>"", "hypervisor_username"=>"", "hypervisor_password"=>"[FILTERED]", "interval"=>"120", "satellite_url"=>"devel.katello.lan", "hypervisor_id"=>"hostname", "listing_mode"=>"0", "whitelist"=>"", "blacklist"=>"", "filter_host_parents"=>"", "exclude_host_parents"=>"", "debug"=>"0", "http_proxy_id"=>"", "no_proxy"=>"", "kubeconfig_path"=>"/tmp/food"}, "commit"=>"Submit"}
```

### Results with patch:

```bash
[vagrant@hammer ~]$ hammer virt-who-config create --name="gCBHwsVPFs" --debug="1" --interval="60" --hypervisor-id="hostname" --hypervisor-type="kubevirt" --organization-id="1" --filtering-mode="none" --satellite-url="ent-02-vm-03.lab.eng.nay.redhat.com" --kubeconfig-path="/root/kube.conf"

Virt Who configuration [gCBHwsVPFs] created
```
#### When not passing the param:
```
[vagrant@hammer hammer-cli-foreman-virt-who-configure]$ hammer virt-who-config create --name="gCBHwsVPFss" --debug="1" --interval="60" --hypervisor-id="hostname" --hypervisor-type="kubevirt" --organization-id="1" --filtering-mode="none" --satellite-url="ent-02-vm-03.lab.eng.nay.redhat.com"

kubeconfig_path parameter is required when using Kubevirt hypervisor type.
```
#### When trying to use the param with another type of hypervisor:
```bash
hammer virt-who-config create --name="gCBHwsVPF6" --debug="1" --interval="60" --hypervisor-id="hostname" --hypervisor-type="esx" --organization-id="1" --filtering-mode="none" --satellite-url="ent-02-vm-03.lab.eng.nay.redhat.com" --hypervisor-server="vcenter.example.com" --hypervisor-username="admin" --hypervisor-password="food" --kubeconfig-path='/tmp/food'

kubeconfig_path parameter is only used when using Kubevirt hypervisor type.
```
#### Update still works
```
[vagrant@hammer ~]$ hammer virt-who-config update --id 3 --kubeconfig-path '/tmp/burgers'
Virt Who configuration [gCBHwsVPFs] updated
```

### CODE REVIEW

**Comment by jturel** [comment]
If I understand your description right, it sounds like hypervisor username and password shouldn't be required on the API side for kubevirt, and that kubeconfig-path should be a valid API param

**Comment by chris1984** [comment]
> If I understand your description right, it sounds like hypervisor username and password shouldn't be required on the API side for kubevirt, and that kubeconfig-path should be a valid API param

That is correct, if i try to make a config for kubevirt without those options in the cli it fails saying they are required. That is why I posted the POST from the UI and saw it was just sending them as empty strings.

**Comment by jturel** [comment]
> > If I understand your description right, it sounds like hypervisor username and password shouldn't be required on the API side for kubevirt, and that kubeconfig-path should be a valid API param
> 
> That is correct, if i try to make a config for kubevirt without those options in the cli it fails saying they are required. That is why I posted the POST from the UI and saw it was just sending them as empty strings.

Would it be better to fix this on the API side then?

**Comment by chris1984** [comment]
> > > If I understand your description right, it sounds like hypervisor username and password shouldn't be required on the API side for kubevirt, and that kubeconfig-path should be a valid API param
> > 
> > 
> > That is correct, if i try to make a config for kubevirt without those options in the cli it fails saying they are required. That is why I posted the POST from the UI and saw it was just sending them as empty strings.
> 
> Would it be better to fix this on the API side then?

You make a good point, I will work on a pr on that side instead of this hack

**Comment by jturel** [comment]
> 
> 
> > > > If I understand your description right, it sounds like hypervisor username and password shouldn't be required on the API side for kubevirt, and that kubeconfig-path should be a valid API param
> > > 
> > > 
> > > That is correct, if i try to make a config for kubevirt without those options in the cli it fails saying they are required. That is why I posted the POST from the UI and saw it was just sending them as empty strings.
> > 
> > 
> > Would it be better to fix this on the API side then?
> 
> You make a good point, I will work on a pr on that side instead of this hack

👍 otherwise anyone using the API directly would have to work around it like you did here :)

**Pull request closed without merging**
